site_name: SciWork Docs
site_description: Utilities and libraries for scientific workflows
site_url: https://VitPavelka.github.io/sciwork/
repo_url: https://github.com/VitPavelka/sciwork
repo_name: sciwork
strict: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: sphinx
            merge_init_into_class: true
            show_source: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Imports:
      - Overview: imports/index.md
  - Config:
      - Overview: config/index.md
      - Tutorial: config/robust-config.md
      - API Reference: config/api.md
  - Console:
      - Overview: console/index.md
      - Printer: console/printer.md
      - Prompt & Confirm: console/prompt.md
      - Console: console/console.md
      - API Reference: console/api.md
  - PathOps:
      - Overview: fs/index.md