site_name: SciWork Docs
site_description: Utilities and libraries for scientific workflows
site_url: https://VitPavelka.github.io/sciwork/
repo_url: https://github.com/VitPavelka/sciwork
repo_name: sciwork
strict: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: sphinx
            merge_init_into_class: true
            show_source: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Imports:
      - Overview: imports/index.md
  - Config:
      - Overview: config/index.md
      - Tutorial: config/robust-config.md
      - API Reference: config/api.md
  - Console:
      - Overview: console/index.md
      - Printer: console/printer.md
      - Prompt & Confirm: console/prompt.md
      - Console: console/console.md
      - API Reference: console/api.md
  - PathOps:
      - Overview: fs/index.md
      - PathOps basics: fs/pathops.md
      - Modules:
          - Overview: fs/pathops/index.md
          - Paths: fs/pathops/paths.md
          - Dirs: fs/pathops/dirs.md
          - Create: fs/pathops/create.md
          - Delete: fs/pathops/delete.md
          - Transfer: fs/pathops/transfer.md
          - GetContents: fs/pathops/getcontents.md
          - Select: fs/pathops/select.md
          - Open: fs/pathops/open.md
          - TreeOps: fs/pathops/treeops.md
          - Archives: fs/pathops/archives.md
          - Load: fs/pathops/load.md
          - Names: fs/pathops/names.md
      - Recipes: fs/recipes.md
      - API Reference: fs/api.md
  - Stats:
      - Overview: stats/index.md
      - MathStat workflows: stats/mathstat.md
      - API Reference: stats/api.md
  - Plot:
      - Overview: plot/index.md
      - Plot workflows: plot/plot.md
      - Plot module guide: plot/modules.md
      - API Reference: plot/api.md