name: docs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# necessary for Pages (official actions request these permissions)
permissions:
  contents: read
  pages: write
  id-token: write

# concurrency is needed to prevent multiple builds from running at the same time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install docs dependencies
        run: |
          python -m pip install -U pip
          pip install -e.[docs]

      - name: Build MkDocs site
        run: mkdocs build --strict

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
